const COUNTRIES = [
  {
    "Country Code": "USA",
    English: "U.S.",
    Korean: "미국",
    Japanese: "アメリカ合衆国",
    Chinese: "美国",
  },
  {
    "Country Code": "JPN",
    English: "Japan",
    Korean: "일본",
    Japanese: "日本",
    Chinese: "日本",
  },
  {
    "Country Code": "GBR",
    English: "U.K.",
    Korean: "영국",
    Japanese: "イギリス",
    Chinese: "英国",
  },
  {
    "Country Code": "DEU",
    English: "Germany",
    Korean: "독일",
    Japanese: "ドイツ",
    Chinese: "德国",
  },
  {
    "Country Code": "CAN",
    English: "Canada",
    Korean: "캐나다",
    Japanese: "カナダ",
    Chinese: "加拿大",
  },
  {
    "Country Code": "AUS",
    English: "Australia",
    Korean: "호주",
    Japanese: "オーストラリア",
    Chinese: "澳大利亚",
  },
  {
    "Country Code": "KOR",
    English: "South Korea",
    Korean: "대한민국",
    Japanese: "韓国",
    Chinese: "韩国",
  },
  {
    "Country Code": "FRA",
    English: "France",
    Korean: "프랑스",
    Japanese: "フランス",
    Chinese: "法国",
  },
  {
    "Country Code": "BRA",
    English: "Brazil",
    Korean: "브라질",
    Japanese: "ブラジル",
    Chinese: "巴西",
  },
  {
    "Country Code": "MEX",
    English: "Mexico",
    Korean: "멕시코",
    Japanese: "メキシコ",
    Chinese: "墨西哥",
  },
  {
    "Country Code": "IND",
    English: "India",
    Korean: "인도",
    Japanese: "インド",
    Chinese: "印度",
  },
  {
    "Country Code": "IDN",
    English: "Indonesia",
    Korean: "인도네시아",
    Japanese: "インドネシア",
    Chinese: "印度尼西亚",
  },
  {
    "Country Code": "VNM",
    English: "Vietnam",
    Korean: "베트남",
    Japanese: "ベトナム",
    Chinese: "越南",
  },
  {
    "Country Code": "All countries",
    English: "All countries",
    Korean: "모든 국가",
    Japanese: "すべての国",
    Chinese: "中国台湾/中国香港",
  },
  {
    "Country Code": "RUS",
    English: "Russia",
    Korean: "러시아",
    Japanese: "ロシア",
    Chinese: "俄罗斯",
  },
  {
    "Country Code": "TUR",
    English: "Turkey",
    Korean: "터키",
    Japanese: "トルコ",
    Chinese: "土耳其",
  },
  {
    "Country Code": "PHL",
    English: "Philippines",
    Korean: "필리핀",
    Japanese: "フィリピン",
    Chinese: "菲律宾",
  },
  {
    "Country Code": "PAK",
    English: "Pakistan",
    Korean: "파키스탄",
    Japanese: "パキスタン",
    Chinese: "巴基斯坦",
  },
  {
    "Country Code": "NGA",
    English: "Nigeria",
    Korean: "나이지리아",
    Japanese: "ナイジェリア",
    Chinese: "尼日利亚",
  },
  {
    "Country Code": "EGY",
    English: "Egypt",
    Korean: "이집트",
    Japanese: "エジプト",
    Chinese: "埃及",
  },
  {
    "Country Code": "THA",
    English: "Thailand",
    Korean: "태국",
    Japanese: "タイ",
    Chinese: "泰国",
  },
  {
    "Country Code": "ITA",
    English: "Italy",
    Korean: "이탈리아",
    Japanese: "イタリア",
    Chinese: "意大利",
  },
  {
    "Country Code": "COL",
    English: "Colombia",
    Korean: "콜롬비아",
    Japanese: "コロンビア",
    Chinese: "哥伦比亚",
  },
  {
    "Country Code": "ESP",
    English: "Spain",
    Korean: "스페인",
    Japanese: "スペイン",
    Chinese: "西班牙",
  },
  {
    "Country Code": "ARG",
    English: "Argentina",
    Korean: "아르헨티나",
    Japanese: "アルゼンチン",
    Chinese: "阿根廷",
  },
  {
    "Country Code": "MYS",
    English: "Malaysia",
    Korean: "말레이시아",
    Japanese: "マレーシア",
    Chinese: "马来西亚",
  },
  {
    "Country Code": "SAU",
    English: "Saudi Arabia",
    Korean: "사우디아라비아",
    Japanese: "サウジアラビア",
    Chinese: "沙特阿拉伯",
  },
  {
    "Country Code": "PER",
    English: "Peru",
    Korean: "페루",
    Japanese: "ペルー",
    Chinese: "秘鲁",
  },
  {
    "Country Code": "ZAF",
    English: "South Africa",
    Korean: "남아프리카공화국",
    Japanese: "南アフリカ",
    Chinese: "南非",
  },
  {
    "Country Code": "DZA",
    English: "Algeria",
    Korean: "알제리",
    Japanese: "アルジェリア",
    Chinese: "阿尔及利亚",
  },
  {
    "Country Code": "UKR",
    English: "Ukraine",
    Korean: "우크라이나",
    Japanese: "ウクライナ",
    Chinese: "乌克兰",
  },
  {
    "Country Code": "VEN",
    English: "Venezuela",
    Korean: "베네수엘라",
    Japanese: "ベネズエラ",
    Chinese: "委内瑞拉",
  },
  {
    "Country Code": "POL",
    English: "Poland",
    Korean: "폴란드",
    Japanese: "ポーランド",
    Chinese: "波兰",
  },
  {
    "Country Code": "CHL",
    English: "Chile",
    Korean: "칠레",
    Japanese: "チリ",
    Chinese: "智利",
  },
  {
    "Country Code": "KAZ",
    English: "Kazakhstan",
    Korean: "카자흐스탄",
    Japanese: "カザフスタン",
    Chinese: "哈萨克斯坦",
  },
  {
    "Country Code": "TWN",
    English: "Taiwan",
    Korean: "대만",
    Japanese: "台湾",
    Chinese: "中国台湾",
  },
  {
    "Country Code": "UZB",
    English: "Uzbekistan",
    Korean: "우즈베키스탄",
    Japanese: "ウズベキスタン",
    Chinese: "乌兹别克斯坦",
  },
  {
    "Country Code": "ECU",
    English: "Ecuador",
    Korean: "에콰도르",
    Japanese: "エクアドル",
    Chinese: "厄瓜多尔",
  },
  {
    "Country Code": "KEN",
    English: "Kenya",
    Korean: "케냐",
    Japanese: "ケニア",
    Chinese: "肯尼亚",
  },
  {
    "Country Code": "LKA",
    English: "Sri Lanka",
    Korean: "스리랑카",
    Japanese: "スリランカ",
    Chinese: "斯里兰卡",
  },
  {
    "Country Code": "GHA",
    English: "Ghana",
    Korean: "가나",
    Japanese: "ガーナ",
    Chinese: "加纳",
  },
  {
    "Country Code": "NLD",
    English: "Netherlands",
    Korean: "네덜란드",
    Japanese: "オランダ",
    Chinese: "荷兰",
  },
  {
    "Country Code": "ROU",
    English: "Romania",
    Korean: "루마니아",
    Japanese: "ルーマニア",
    Chinese: "罗马尼亚",
  },
  {
    "Country Code": "ARE",
    English: "UAE",
    Korean: "아랍에미리트",
    Japanese: "アラブ首長国連邦",
    Chinese: "阿拉伯联合酋长国",
  },
  {
    "Country Code": "DOM",
    English: "Dominican Republic",
    Korean: "도미니카공화국",
    Japanese: "ドミニカ共和国",
    Chinese: "多米尼加共和国",
  },
  {
    "Country Code": "GTM",
    English: "Guatemala",
    Korean: "과테말라",
    Japanese: "グアテマラ",
    Chinese: "危地马拉",
  },
  {
    "Country Code": "AZE",
    English: "Azerbaijan",
    Korean: "아제르바이잔",
    Japanese: "アゼルバイジャン",
    Chinese: "阿塞拜疆",
  },
  {
    "Country Code": "ISR",
    English: "Israel",
    Korean: "이스라엘",
    Japanese: "イスラエル",
    Chinese: "以色列",
  },
  {
    "Country Code": "TUN",
    English: "Tunisia",
    Korean: "튀니지",
    Japanese: "チュニジア",
    Chinese: "突尼斯",
  },
  {
    "Country Code": "PRT",
    English: "Portugal",
    Korean: "포르투갈",
    Japanese: "ポルトガル",
    Chinese: "葡萄牙",
  },
  {
    "Country Code": "BEL",
    English: "Belgium",
    Korean: "벨기에",
    Japanese: "ベルギー",
    Chinese: "比利时",
  },
  {
    "Country Code": "LBN",
    English: "Lebanon",
    Korean: "레바논",
    Japanese: "レバノン",
    Chinese: "黎巴嫩",
  },
  {
    "Country Code": "SWE",
    English: "Sweden",
    Korean: "스웨덴",
    Japanese: "スウェーデン",
    Chinese: "瑞典",
  },
  {
    "Country Code": "GRC",
    English: "Greece",
    Korean: "그리스",
    Japanese: "ギリシャ",
    Chinese: "希腊",
  },
  {
    "Country Code": "CZE",
    English: "Czechia",
    Korean: "체코",
    Japanese: "チェコ",
    Chinese: "捷克",
  },
  {
    "Country Code": "BLR",
    English: "Belarus",
    Korean: "벨라루스",
    Japanese: "ベラルーシ",
    Chinese: "白俄罗斯",
  },
  {
    "Country Code": "HUN",
    English: "Hungary",
    Korean: "헝가리",
    Japanese: "ハンガリー",
    Chinese: "匈牙利",
  },
  {
    "Country Code": "HKG",
    English: "Hong Kong SAR",
    Korean: "홍콩 특별행정구",
    Japanese: "香港特別行政区",
    Chinese: "中国香港",
  },
  {
    "Country Code": "CRI",
    English: "Costa Rica",
    Korean: "코스타리카",
    Japanese: "コスタリカ",
    Chinese: "哥斯达黎加",
  },
  {
    "Country Code": "SGP",
    English: "Singapore",
    Korean: "싱가포르",
    Japanese: "シンガポール",
    Chinese: "新加坡",
  },
  {
    "Country Code": "SLV",
    English: "El Salvador",
    Korean: "엘살바도르",
    Japanese: "エルサルバドル",
    Chinese: "萨尔瓦多",
  },
  {
    "Country Code": "OMN",
    English: "Oman",
    Korean: "오만",
    Japanese: "オマーン",
    Chinese: "阿曼",
  },
  {
    "Country Code": "CHE",
    English: "Switzerland",
    Korean: "스위스",
    Japanese: "スイス",
    Chinese: "瑞士",
  },
  {
    "Country Code": "KWT",
    English: "Kuwait",
    Korean: "쿠웨이트",
    Japanese: "クウェート",
    Chinese: "科威特",
  },
  {
    "Country Code": "AUT",
    English: "Austria",
    Korean: "오스트리아",
    Japanese: "オーストリア",
    Chinese: "奥地利",
  },
  {
    "Country Code": "BGR",
    English: "Bulgaria",
    Korean: "불가리아",
    Japanese: "ブルガリア",
    Chinese: "保加利亚",
  },
  {
    "Country Code": "IRL",
    English: "Ireland",
    Korean: "아일랜드",
    Japanese: "アイルランド",
    Chinese: "爱尔兰",
  },
  {
    "Country Code": "PAN",
    English: "Panama",
    Korean: "파나마",
    Japanese: "パナマ",
    Chinese: "巴拿马",
  },
  {
    "Country Code": "NZL",
    English: "New Zealand",
    Korean: "뉴질랜드",
    Japanese: "ニュージーランド",
    Chinese: "新西兰",
  },
  {
    "Country Code": "FIN",
    English: "Finland",
    Korean: "핀란드",
    Japanese: "フィンランド",
    Chinese: "芬兰",
  },
  {
    "Country Code": "DNK",
    English: "Denmark",
    Korean: "덴마크",
    Japanese: "デンマーク",
    Chinese: "丹麦",
  },
  {
    "Country Code": "URY",
    English: "Uruguay",
    Korean: "우루과이",
    Japanese: "ウルグアイ",
    Chinese: "乌拉圭",
  },
  {
    "Country Code": "NOR",
    English: "Norway",
    Korean: "노르웨이",
    Japanese: "ノルウェー",
    Chinese: "挪威",
  },
  {
    "Country Code": "QAT",
    English: "Qatar",
    Korean: "카타르",
    Japanese: "カタール",
    Chinese: "卡塔尔",
  },
  {
    "Country Code": "HRV",
    English: "Croatia",
    Korean: "크로아티아",
    Japanese: "クロアチア",
    Chinese: "克罗地亚",
  },
  {
    "Country Code": "SVK",
    English: "Slovakia",
    Korean: "슬로바키아",
    Japanese: "スロバキア",
    Chinese: "斯洛伐克",
  },
  {
    "Country Code": "LTU",
    English: "Lithuania",
    Korean: "리투아니아",
    Japanese: "リトアニア",
    Chinese: "立陶宛",
  },
  {
    "Country Code": "SVN",
    English: "Slovenia",
    Korean: "슬로베니아",
    Japanese: "スロベニア",
    Chinese: "斯洛文尼亚",
  },
  {
    "Country Code": "AGO",
    English: "Angola",
    Korean: "앙골라",
    Japanese: "アンゴラ",
    Chinese: "安哥拉",
  },
  {
    "Country Code": "LUX",
    English: "Luxembourg",
    Korean: "룩셈부르크",
    Japanese: "ルクセンブルク",
    Chinese: "卢森堡",
  },
  {
    "Country Code": "MDG",
    English: "Madagascar",
    Korean: "마다가스카르",
    Japanese: "マダガスカル",
    Chinese: "马达加斯加",
  },
  {
    "Country Code": "BRB",
    English: "Barbados",
    Korean: "바베이도스",
    Japanese: "バルバドス",
    Chinese: "巴巴多斯",
  },
  {
    "Country Code": "BMU",
    English: "Bermuda",
    Korean: "버뮤다",
    Japanese: "バミューダ",
    Chinese: "百慕大",
  },
  {
    "Country Code": "Australia",
    English: "AUS",
    Korean: "AUS",
    Japanese: "AUS",
    Chinese: "澳大利亚",
  },
  {
    "Country Code": "Brazil",
    English: "BRA",
    Korean: "BRA",
    Japanese: "BRA",
    Chinese: "巴西",
  },
  {
    "Country Code": "Canada",
    English: "CAN",
    Korean: "CAN",
    Japanese: "CAN",
    Chinese: "加拿大",
  },
  {
    "Country Code": "Germany",
    English: "DEU",
    Korean: "DEU",
    Japanese: "DEU",
    Chinese: "德国",
  },
  {
    "Country Code": "France",
    English: "FRA",
    Korean: "FRA",
    Japanese: "FRA",
    Chinese: "法国",
  },
  {
    "Country Code": "South Korea",
    English: "KOR",
    Korean: "KOR",
    Japanese: "KOR",
    Chinese: "韩国",
  },
  {
    "Country Code": "Japan",
    English: "JPN",
    Korean: "JPN",
    Japanese: "JPN",
    Chinese: "日本",
  },
  {
    "Country Code": "U.S.",
    English: "USA",
    Korean: "USA",
    Japanese: "USA",
    Chinese: "美国",
  },
  {
    "Country Code": "Vietnam",
    English: "VNM",
    Korean: "VNM",
    Japanese: "VNM",
    Chinese: "越南",
  },
  {
    "Country Code": "Indonesia",
    English: "IDN",
    Korean: "IDN",
    Japanese: "IDN",
    Chinese: "印度尼西亚",
  },
  {
    "Country Code": "U.K.",
    English: "GBR",
    Korean: "GBR",
    Japanese: "GBR",
    Chinese: "英国",
  },
  {
    "Country Code": "Mexico",
    English: "MEX",
    Korean: "MEX",
    Japanese: "MEX",
    Chinese: "墨西哥",
  },
  {
    "Country Code": "India",
    English: "IND",
    Korean: "IND",
    Japanese: "IND",
    Chinese: "印度",
  },
];

const CATEGORIES = [
  {
    English: "Gaming",
    Korean: "게임",
    Japanese: "ゲーム",
    Chinese: "游戏",
  },
  {
    English: "Non-gaming",
    Korean: "비게임",
    Japanese: "ゲーム以外",
    Chinese: "非游戏",
  },
  {
    English: "Gaming apps",
    Korean: "게임 앱",
    Japanese: "ゲームアプリ",
    Chinese: "游戏 App",
  },
  {
    English: "Consumer apps",
    Korean: "컨슈머 앱",
    Japanese: "消費者向けアプリ",
    Chinese: "消费级 App",
  },
  {
    English: "Consumer",
    Korean: "컨슈머",
    Japanese: "消費者",
    Chinese: "消费者",
  },
  {
    English: "Other Walled Gardens",
    Korean: "기타 월드가든",
    Japanese: "その他のウォールドガーデン",
    Chinese: "其他围墙花园",
  },
  {
    English: "Independent apps",
    Korean: "독립 광고 생태계 내 앱",
    Japanese: "独立系アプリ",
    Chinese: "开放互联网",
  },
  {
    English: "Independent App Ecosystem",
    Korean: "독립 광고 생태계",
    Japanese: "独立系アプリエコシステム",
    Chinese: "开放互联网",
  },
  {
    English: "Entertainment",
    Korean: "엔터테인먼트",
    Japanese: "エンターテインメント",
    Chinese: "娱乐",
  },
  {
    English: "Photo & Video",
    Korean: "사진 및 비디오",
    Japanese: "写真・動画",
    Chinese: "照片和视频",
  },
  {
    English: "Productivity",
    Korean: "생산성",
    Japanese: "生産性",
    Chinese: "生产力工具",
  },
  {
    English: "Lifestyle",
    Korean: "라이프스타일",
    Japanese: "ライフスタイル",
    Chinese: "生活方式",
  },
  {
    English: "Social Networking",
    Korean: "소셜 네트워킹",
    Japanese: "ソーシャルネットワーキング",
    Chinese: "社交网络",
  },
  {
    English: "Health & Fitness",
    Korean: "건강 및 피트니스",
    Japanese: "健康・フィットネス",
    Chinese: "健康与健身",
  },
  {
    English: "Education",
    Korean: "교육",
    Japanese: "教育",
    Chinese: "教育",
  },
  {
    English: "Social",
    Korean: "소셜",
    Japanese: "ソーシャル",
    Chinese: "社交",
  },
  {
    English: "Books",
    Korean: "도서",
    Japanese: "書籍",
    Chinese: "图书",
  },
  {
    English: "Business",
    Korean: "비즈니스",
    Japanese: "ビジネス",
    Chinese: "商业",
  },
  {
    English: "Sports",
    Korean: "스포츠",
    Japanese: "スポーツ",
    Chinese: "体育",
  },
  {
    English: "Utilities",
    Korean: "유틸리티",
    Japanese: "ユーティリティ",
    Chinese: "实用工具",
  },
  {
    English: "Dating",
    Korean: "데이트",
    Japanese: "デート",
    Chinese: "交友",
  },
  {
    English: "Music & Audio",
    Korean: "음악 및 오디오",
    Japanese: "音楽・オーディオ",
    Chinese: "音乐与音频",
  },
  {
    English: "News",
    Korean: "뉴스",
    Japanese: "ニュース",
    Chinese: "新闻",
  },
  {
    English: "Comics",
    Korean: "만화",
    Japanese: "マンガ",
    Chinese: "漫画",
  },
  {
    English: "Books & Reference",
    Korean: "도서 및 참고자료",
    Japanese: "書籍・参考書",
    Chinese: "图书与工具书",
  },
  {
    English: "Video Players & Editors",
    Korean: "동영상 플레이어 및 편집",
    Japanese: "動画再生・編集",
    Chinese: "视频播放器和编辑器",
  },
  {
    English: "Shopping",
    Korean: "쇼핑",
    Japanese: "ショッピング",
    Chinese: "购物",
  },
  {
    English: "Communication",
    Korean: "커뮤니케이션",
    Japanese: "コミュニケーション",
    Chinese: "通讯",
  },
  {
    English: "Finance",
    Korean: "금융",
    Japanese: "ファイナンス",
    Chinese: "金融",
  },
  {
    English: "Graphics & Design",
    Korean: "그래픽 및 디자인",
    Japanese: "グラフィック・デザイン",
    Chinese: "图形和设计",
  },
  {
    English: "Navigation",
    Korean: "내비게이션",
    Japanese: "ナビゲーション",
    Chinese: "导航",
  },
  {
    English: "Tools",
    Korean: "도구",
    Japanese: "ツール",
    Chinese: "工具",
  },
  {
    English: "Photography",
    Korean: "사진",
    Japanese: "写真",
    Chinese: "摄影",
  },
  {
    English: "Reference",
    Korean: "참고",
    Japanese: "参考書",
    Chinese: "参考",
  },
  {
    English: "Weather",
    Korean: "날씨",
    Japanese: "天気",
    Chinese: "天气",
  },
  {
    English: "News & Magazines",
    Korean: "뉴스 및 잡지",
    Japanese: "ニュース・雑誌",
    Chinese: "新闻与杂志",
  },
  {
    English: "Medical",
    Korean: "의료",
    Japanese: "医療",
    Chinese: "医疗",
  },
  {
    English: "Travel",
    Korean: "여행",
    Japanese: "旅行",
    Chinese: "旅游",
  },
  {
    English: "Maps & Navigation",
    Korean: "지도 및 내비게이션",
    Japanese: "地図・ナビゲーション",
    Chinese: "地图与导航",
  },
  {
    English: "Art & Design",
    Korean: "예술 및 디자인",
    Japanese: "アート・デザイン",
    Chinese: "艺术与设计",
  },
  {
    English: "Food & Drink",
    Korean: "음식 및 음료",
    Japanese: "食品・飲料",
    Chinese: "美食佳饮",
  },
  {
    English: "Parenting",
    Korean: "육아",
    Japanese: "子育て",
    Chinese: "亲子",
  },
  {
    English: "Travel & Local",
    Korean: "여행 및 지역",
    Japanese: "旅行＆ローカル",
    Chinese: "旅游与本地",
  },
  {
    English: "Personalization",
    Korean: "개인화",
    Japanese: "パーソナライゼーション",
    Chinese: "个性化",
  },
  {
    English: "Developer Tools",
    Korean: "개발자 도구",
    Japanese: "開発ツール",
    Chinese: "开发者工具",
  },
  {
    English: "Magazines & Newspapers",
    Korean: "잡지 및 신문",
    Japanese: "雑誌・新聞",
    Chinese: "杂志与报纸",
  },
  {
    English: "Auto & Vehicles",
    Korean: "자동차 및 차량",
    Japanese: "自動車＆車両",
    Chinese: "汽车与车辆",
  },
  {
    English: "House & Home",
    Korean: "주택 및 생활",
    Japanese: "住宅＆ホーム",
    Chinese: "房屋与家居",
  },
  {
    English: "Beauty",
    Korean: "뷰티",
    Japanese: "美容",
    Chinese: "美容",
  },
  {
    English: "Events",
    Korean: "이벤트",
    Japanese: "イベント",
    Chinese: "活动",
  },
  {
    English: "Libraries & Demo",
    Korean: "라이브러리 및 데모",
    Japanese: "ライブラリ＆デモ",
    Chinese: "库和演示",
  },
  {
    English: "Media & Video",
    Korean: "미디어 및 비디오",
    Japanese: "メディア・動画",
    Chinese: "媒体与视频",
  },
  {
    English: "Stickers",
    Korean: "스티커",
    Japanese: "ステッカー",
    Chinese: "贴纸",
  },
  {
    English: "Transportation",
    Korean: "교통",
    Japanese: "交通",
    Chinese: "交通",
  },
  {
    English: "Catalogs",
    Korean: "카탈로그",
    Japanese: "カタログ",
    Chinese: "目录",
  },
  {
    English: "Music",
    Korean: "음악",
    Japanese: "音楽",
    Chinese: "音乐",
  },
  {
    English: "Financial",
    Korean: "금융",
    Japanese: "ファイナンス",
    Chinese: "金融",
  },
  {
    English: "On-Demand",
    Korean: "주문형",
    Japanese: "オンデマンド",
    Chinese: "按需服务",
  },
  {
    English: "Other",
    Korean: "기타",
    Japanese: "その他",
    Chinese: "其他",
  },
  {
    English: "Delivery & Food",
    Korean: "배달 및 음식",
    Japanese: "デリバリー & フード",
    Chinese: "配送与餐饮",
  },
  {
    English: "Social Media",
    Korean: "소셜 미디어",
    Japanese: "ソーシャルメディア",
    Chinese: "社交媒体",
  },
  {
    English: "Utility & Productivity",
    Korean: "유틸리티 및 생산성",
    Japanese: "ユーティリティ & 生産性",
    Chinese: "实用与效率",
  },
  {
    English: "Generative AI",
    Korean: "생성형 AI",
    Japanese: "生成AI",
    Chinese: "生成式 AI",
  },
  {
    English: "Health and Fitness",
    Korean: "건강 및 피트니스",
    Japanese: "健康・フィットネス",
    Chinese: "健康与健身",
  },
  {
    English: "Games / Strategy",
    Korean: "게임/전략",
    Japanese: "ゲーム / 戦略",
    Chinese: "游戏/策略",
  },
  {
    English: "Games / Puzzle",
    Korean: "게임/퍼즐",
    Japanese: "ゲーム / パズル",
    Chinese: "游戏/解谜",
  },
  {
    English: "Games / Casino",
    Korean: "게임/카지노",
    Japanese: "ゲーム / カジノ",
    Chinese: "游戏/赌场",
  },
  {
    English: "RMG",
    Korean: "RMG",
    Japanese: "RMG",
    Chinese: "真金游戏",
  },
  {
    English: "E-Commerce",
    Korean: "이커머스",
    Japanese: "Eコマース",
    Chinese: "电子商务",
  },
  {
    English: "On Demand",
    Korean: "주문형",
    Japanese: "オンデマンド",
    Chinese: "按需服务",
  },
  {
    English: "Casino Games",
    Korean: "카지노 게임",
    Japanese: "カジノゲーム",
    Chinese: "赌场游戏",
  },
  {
    English: "Casual Games",
    Korean: "캐주얼 게임",
    Japanese: "カジュアルゲーム",
    Chinese: "休闲游戏",
  },
  {
    English: "Games / Sports",
    Korean: "게임/스포츠",
    Japanese: "ゲーム / スポーツ",
    Chinese: "游戏/体育",
  },
  {
    English: "Automotive",
    Korean: "자동차",
    Japanese: "自動車",
    Chinese: "汽车",
  },
  {
    English: "Family & Relationships",
    Korean: "가족 및 관계",
    Japanese: "家族・人間関係",
    Chinese: "家庭与关系",
  },
  {
    English: "Graphic & Design",
    Korean: "그래픽 및 디자인",
    Japanese: "グラフィック・デザイン",
    Chinese: "图形与设计",
  },
  {
    English: "Real Estate",
    Korean: "부동산",
    Japanese: "不動産",
    Chinese: "房地产",
  },
  {
    English: "Travel & Navigation",
    Korean: "여행 및 내비게이션",
    Japanese: "旅行 & ナビゲーション",
    Chinese: "旅行与导航",
  },
  {
    English: "Food & Delivery",
    Korean: "음식 및 배달",
    Japanese: "フード & デリバリー",
    Chinese: "餐饮与配送",
  },
  {
    English: "Other Consumer Publishers",
    Korean: "기타 컨슈머 퍼블리셔",
    Japanese: "その他の消費者向けパブリッシャー",
    Chinese: "其他消费者发行商",
  },
];

const VIZ1_LABELS = [
  {
    English: "2024 vs. 2023 growth",
    Korean: "",
    Japanese: "2024年の収益成長（2023年との比較）",
    Chinese: "2024 年增长 vs 2023 年增长",
  },
  {
    English: "Revenue",
    Korean: "",
    Japanese: "収益",
    Chinese: "收入",
  },
];

const VIZ4_LABELS = [
  {
    English: "Baseline",
    Korean: "",
    Japanese: "ベースライン",
    Chinese: "基准线",
  },
];

const VIZ6_LABELS = [
  // year labels are not used in the chart, so commented out
  // {
  //   English: "2021",
  //   Korean: "",
  //   Japanese: "2021年",
  //   Chinese: "2021 年",
  // },
  // {
  //   English: "2024",
  //   Korean: "",
  //   Japanese: "2024年",
  //   Chinese: "2024 年",
  // },
  {
    English: "+/-X%",
    Korean: "",
    Japanese: "+/-X%",
    Chinese: "+/-X%",
  },
  {
    English: "Compound Annual Growth Rate (CAGR)",
    Korean: "",
    Japanese: "年平均成長率（CAGR)",
    Chinese: "复合年增长率（CAGR）",
  },
  {
    English: "Top 10 mobile app markets",
    Korean: "",
    Japanese: "モバイルアプリ市場上位10か国",
    Chinese: "Top10 移动应用市场",
  },
  // added manually to allow axis break filtering for Asia
  {
    English: "Asia",
    Korean: "",
    Japanese: "アジア",
    Chinese: "亚洲",
  },
];

const VIZ8_LABELS = [
  {
    English: "Less time",
    Korean: "",
    Japanese: "より少ない時間",
    Chinese: "使用时长更少",
  },
  {
    English: "More time",
    Korean: "",
    Japanese: "より多くの時間",
    Chinese: "使用时长更多",
  },
  {
    English: "Show more",
    Korean: "",
    Japanese: "もっと見る",
    Chinese: "显示更多",
  },
  {
    English: "Show less",
    Korean: "",
    Japanese: "表示を減らす",
    Chinese: "显示更少",
  },
  {
    English: "18-24 years old",
    Korean: "",
    Japanese: "18～24歳",
    Chinese: "18-24",
  },
  {
    English: "25-44 years old",
    Korean: "",
    Japanese: "25～44歳",
    Chinese: "25-44",
  },
  {
    English: "45+ years old",
    Korean: "",
    Japanese: "45歳以上",
    Chinese: "45+",
  },
  {
    English: "Country",
    Korean: "",
    Japanese: "国名",
    Chinese: "国家/地区",
  },
  {
    English: "Age group",
    Korean: "",
    Japanese: "年齢層",
    Chinese: "年龄段",
  },
  {
    English: "Time spent vs. general population",
    Korean: "",
    Japanese: "一般人口との利用時間の比較",
    Chinese: "使用时长与用户总数的对比",
  },
];
const VIZ9_LABELS = [
  {
    English: "Independent App Ecosystem",
    Korean: "",
    Japanese: "独立系アプリエコシステム",
    Chinese: "开放互联网",
  },
  {
    English: "DAU",
    Korean: "",
    Japanese: "DAU",
    Chinese: "DAU",
  },
  {
    English: "Time spent",
    Korean: "",
    Japanese: "利用時間",
    Chinese: "使用时长",
  },
  {
    English: "Country",
    Korean: "",
    Japanese: "国名",
    Chinese: "国家或地区",
  },
  {
    English: "Platform",
    Korean: "",
    Japanese: "プラットフォーム",
    Chinese: "平台",
  },
  {
    English: "Daily active users",
    Korean: "",
    Japanese: "デイリーアクティブユーザー数",
    Chinese: "日活用户",
  },
  {
    English: "Time spent (in hours)",
    Korean: "",
    Japanese: "利用時間（時間単位）",
    Chinese: "使用时长（小时）",
  },
];

const VIZ10_LABELS = [
  {
    English: "You can only select 3 countries",
    Korean: "",
    Japanese: "最大3つまで選択できます",
    Chinese: "您只能选择 3 个国家/地区",
  },
  {
    English: "Time spent in-app (% of total)",
    Korean: "",
    Japanese: "アプリの利用時間（全体に対する割合）",
    Chinese: "App 使用时长（占总时间的百分比）",
  },
  {
    English: "Less time",
    Korean: "",
    Japanese: "少ない",
    Chinese: "使用时长更少",
  },
  {
    English: "More time",
    Korean: "",
    Japanese: "多い",
    Chinese: "使用时长更多",
  },
  {
    English: "Time spent in 2024 vs. 2023",
    Korean: "",
    Japanese: "2023年と2024年の利用時間の比較",
    Chinese: "2024 年与 2023 年使用时长对比",
  },
  {
    English: "Increasing",
    Korean: "",
    Japanese: "増加",
    Chinese: "增加",
  },
  {
    English: "Decreasing",
    Korean: "",
    Japanese: "減少",
    Chinese: "减少",
  },
  {
    English: "Add another country to compare",
    Korean: "",
    Japanese: "比較する国を追加する",
    Chinese: "添加另一个国家/地区进行比较",
  },
  {
    English: "Total time spent share",
    Korean: "",
    Japanese: "総利用時間の割合",
    Chinese: "总使用时长百分比",
  },
  {
    English: "Growth (2023-2024)",
    Korean: "",
    Japanese: "成長率（2023～2024年）",
    Chinese: "增长率（2023-2024）",
  },
];
const VIZ11_LABELS = [
  {
    English: "IAE apps used in a month",
    Korean: "",
    Japanese: "1か月間に利用された独立系アプリ",
    Chinese: "一个月内使用的 IAE 移动应用",
  },
  {
    English: "Ad opportunities in 24 hours",
    Korean: "",
    Japanese: "24時間の広告機会",
    Chinese: "24 小时内的广告机会",
  },
  {
    English: "Where users spend their time",
    Korean: "",
    Japanese: "利用しているアプリの種類",
    Chinese: "用户花费时间的 App",
  },
  {
    English: "Time spent vs. general population",
    Korean: "",
    Japanese: "一般人口との利用時間の比較",
    Chinese: "人群和使用时长的对比",
  },
  {
    English: "Global ad-supported apps",
    Korean: "",
    Japanese: "広告に対応しているグローバルアプリ",
    Chinese: "全球受广告支持的 App",
  },
  {
    English: "Example publisher inventory",
    Korean: "",
    Japanese: "パブリッシャー在庫の例",
    Chinese: "发行商投放示例",
  },
  {
    English: "Age and gender split",
    Korean: "",
    Japanese: "年齢・性別による分布",
    Chinese: "年龄和性别分布",
  },
];

const VIZ12_LABELS = [
  {
    English: "You can only select 4 categories",
    Korean: "",
    Japanese: "最大4つまで選択できます",
    Chinese: "您最多可选择 4 个类别",
  },
  {
    English: "Add another category to compare",
    Korean: "",
    Japanese: "比較するカテゴリーを追加する",
    Chinese: "添加另一个 App 类别进行比较",
  },
  {
    English: "No sufficient data for this category",
    Korean: "",
    Japanese: "このカテゴリーに関する十分なデータがありません",
    Chinese: "该 App 类别的数据不足",
  },
  {
    English: "5am",
    Korean: "",
    Japanese: "5am",
    Chinese: "上午 5 点",
  },
  {
    English: "8am",
    Korean: "",
    Japanese: "8am",
    Chinese: "上午 8 点",
  },
  {
    English: "11am",
    Korean: "",
    Japanese: "11am",
    Chinese: "上午 11 点",
  },
  {
    English: "2pm",
    Korean: "",
    Japanese: "2pm",
    Chinese: "下午 2 点",
  },
  {
    English: "5pm",
    Korean: "",
    Japanese: "5pm",
    Chinese: "下午 5 点",
  },
  {
    English: "8pm",
    Korean: "",
    Japanese: "8pm",
    Chinese: "下午 8 点",
  },
  {
    English: "11pm",
    Korean: "",
    Japanese: "11pm",
    Chinese: "下午 11 点",
  },
  {
    English: "2am",
    Korean: "",
    Japanese: "2am",
    Chinese: "上午 2 点",
  },
];

const VIZ13_LABELS = [
  {
    English: "Indexed CPP",
    Korean: "",
    Japanese: "CPP指数",
    Chinese: "CPP 指数",
  },
  {
    English: "Advertiser category",
    Korean: "",
    Japanese: "広告主カテゴリー",
    Chinese: "广告主类别",
  },
  {
    English: "All categories",
    Korean: "",
    Japanese: "すべてのカテゴリー",
    Chinese: "全部类别",
  },
  {
    English: "Books & Reference",
    Korean: "",
    Japanese: "書籍・参考書",
    Chinese: "图书与工具书",
  },
  {
    English: "Entertainment",
    Korean: "",
    Japanese: "エンターテインメント",
    Chinese: "娱乐",
  },
  {
    English: "Gaming",
    Korean: "",
    Japanese: "ゲーム",
    Chinese: "游戏",
  },
  {
    English: "Health & Fitness",
    Korean: "",
    Japanese: "健康・フィットネス",
    Chinese: "健康与健身",
  },
  {
    English: "Other Consumer",
    Korean: "",
    Japanese: "その他の消費者向けアプリ",
    Chinese: "其他消费类别",
  },
  {
    English: "Photo & Video",
    Korean: "",
    Japanese: "写真・動画",
    Chinese: "照片和视频",
  },
  {
    English: "Social Media",
    Korean: "",
    Japanese: "ソーシャルメディア",
    Chinese: "社交媒体",
  },
  {
    English: "Utility & Productivity",
    Korean: "",
    Japanese: "ユーティリティ & 生産性",
    Chinese: "实用与效率",
  },
  {
    English: "Advertiser category",
    Korean: "",
    Japanese: "広告主のカテゴリー",
    Chinese: "广告主类别",
  },
  {
    English: "Publisher category",
    Korean: "",
    Japanese: "パブリッシャーのカテゴリー",
    Chinese: "发行商类别",
  },
  {
    English: "Indexed cost per payer",
    Korean: "",
    Japanese: "コンバージョン単価指標",
    Chinese: "每付费用户成本指数",
  },
];

const labelMap = {
  1: VIZ1_LABELS,
  // 2: labels for viz 2 only used in Figma, so not needed in code here
  4: VIZ4_LABELS,
  6: VIZ6_LABELS,
  7: [], // no special labels for viz 7
  8: VIZ8_LABELS,
  9: VIZ9_LABELS,
  10: VIZ10_LABELS,
  11: VIZ11_LABELS,
  12: VIZ12_LABELS,
  13: VIZ13_LABELS,
};

const localeMap = {
  en: "English",
  ko: "Korean",
  ja: "Japanese",
  zh: "Chinese",
};

export function getLabel(vizId, locale, key) {
  // console.log("getLabel called with:", vizId, locale, key);
  const labels = (labelMap[vizId] || []).concat(COUNTRIES, CATEGORIES);

  const labelObj = labels.find((label) => Object.values(label).includes(key));
  if (labelObj && labelObj[localeMap[locale]] !== "") {
    return labelObj[localeMap[locale]];
  }
  return "!" + key;
}
